### ISSUE TITLE
Can't use LifecycleManager in v1.13.4

### ISSUE THREAD

**Issue by asafm** [Netflix/governator#311]
When we upgraded from 1.12.13 to 1.13.4 we can't create the injector due to this exception 

```
1) Explicit bindings are required and com.netflix.governator.LifecycleManager is not explicitly bound.
  while locating com.netflix.governator.LifecycleManager
    for parameter 0 at com.netflix.governator.LifecycleListenerModule$LifecycleListenerProvisionListener.initialize(LifecycleListenerModule.java:43)
  at com.netflix.governator.LifecycleListenerModule$LifecycleListenerProvisionListener.initialize(LifecycleListenerModule.java:43)
  at com.netflix.governator.LifecycleListenerModule.configure(LifecycleListenerModule.java:24)
1 error
    at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:466)
    at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155)
    at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
    at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:226)
    at com.netflix.governator.guice.LifecycleInjector.createChildInjector(LifecycleInjector.java:327)
    at com.netflix.governator.guice.LifecycleInjector.createInjector(LifecycleInjector.java:399)
    at com.netflix.governator.guice.LifecycleInjector.createInjector(LifecycleInjector.java:348)
```

We tracked this bug to start at 1.12.15 (1.12.14 is messed up - lots of compilation errors).

**Comment by tcellucci** [comment]
I suspect the issue lies in how the LifecycleInjector is built, since there
are a number of tests in the governator project that create injectors with
every build (ref: LifeCycleFeaturesOnLegacyBuilderTest) .

 Can you send details on how your code is building LifecycleInjector?

**Comment by tcellucci** [comment]
looking more closely at the error, I think now that the problem is that
your code's LifecycleInjector is configured for 'requireExplicitBindings',
but com.netflix.governator.LifecycleManager is only implicitly bound.
Governator needs to be updated to explicitly bind LifecycleManager as a
singleton; I'll make the fix.

**Comment by asafm** [comment]
@tcellucci - we haven't configured anything special when building LifecycleInjector. I even searched for "requireExplicitBindings" in the builder and in the LifecycleInjector and couldn't find any such method.

So I'll wait for the fix. Any release date planned?

**Comment by asafm** [comment]
@tcellucci Where can I track it?

**Comment by asafm** [comment]
@tcellucci Where can I track the fix?

**Comment by tcellucci** [comment]
@asafm this _is_ the issue tracking system for github, you can track it here. From what you've said (i.e., requireExplicitBindings is not enabled), it's hard to confirm the fix will work for you.   Please send a unit test that reproduces the problem you're seeing.

**Comment by asafm** [comment]
@tcellucci Sorry for the delay. Here's a full test proving it: https://github.com/logzio/governator-bug. We'll delete that repo once we're done with this bug.

**Comment by asafm** [comment]
@tcellucci Ping

**Comment by asafm** [comment]
Tested against 1.17.0 and issue solved.
